name: Clock
description: "Clock Made My Rishav"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  audioplayers: ^6.2.0
  timezone: ^0.10.0
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/alarm_clock.mp3
