import 'dart:io';
import 'package:timezone/timezone.dart' as tz;
import 'package:timezone/data/latest.dart' as tz;

void main() {
  tz.initializeTimeZones();
  final timezones = tz.timeZoneDatabase.locations.keys.toList();

  final dartCode = '''
// This file is generated by scripts/generate_timezones.dart
// Do not manually edit this file.

const List<String> allTimezonesList = [
${timezones.map((tz) => '\'$tz\'').join(',\n')}
];
''';

  final file = File('lib/data/timezones.dart'); // Output file path
  // Create the directory if it doesn't exist
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(dartCode);

  print('Timezones saved to lib/data/timezones.dart');
}